services:

  backend:
    build:
      context: ./backend
    container_name: phone-shop-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: phone-shop-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend